defaults:
    - override hydra/launcher: submitit_local

# environment
task: dog-run
obs: state

# evaluation
checkpoint: null # Path to a checkpoint file for evaluation, e.g., /path/to/model.pt
eval_episodes: 10
eval_freq: 50000

# training
steps: 10_000_000
batch_size: 256
reward_coef: 0.1
value_coef: 0.1
consistency_coef: 20
rho: 0.5
lr: 3e-4
enc_lr_scale: 0.3
grad_clip_norm: 20
tau: 0.01
discount_denom: 5
discount_min: 0.95
discount_max: 0.995
buffer_size: 1_000_000
exp_name: default
data_dir: ./data # Directory for offline data (if used)

# ensemble
ensemble_size: 2
ensemble_aggregation: mean
var_coeff: 0.0

# planning
mpc: true
iterations: 6
num_samples: 512
num_elites: 64
num_pi_trajs: 30
horizon: 3
horizon_eval: null
min_std: 0.05
max_std: 2
temperature: 0.5

# actor
log_std_min: -10
log_std_max: 2
entropy_coef: 1e-4

# critic
num_bins: 101
vmin: -10
vmax: +10

# architecture
model_size: 5 # Model size in millions of parameters {1, 5, 19, 48, 317}. Default for single-task is 5.
num_enc_layers: 2
enc_dim: 256
num_channels: 32
mlp_dim: 512
latent_dim: 512
task_dim: 96
num_q: 5
dropout: 0.01
simnorm_dim: 8

# logging
wandb_project: AW-TDMPC2
wandb_entity: samibg
wandb_silent: false
enable_wandb: true
save_csv: false
wandb_name_suffix: ""
save_freq: 100000  # Save agent every N steps
save_best: true   # Whether to save the best performing agent

# misc
save_video: true
save_agent: true
seed: 1

# convenience (these are typically filled automatically by the code)
work_dir: null
task_title: null
multitask: null
tasks: null
obs_shape: null
action_dim: null
episode_length: null
obs_shapes: null
action_dims: null
episode_lengths: null
seed_steps: null
bin_size: null

# speedups
compile: true
